# Generated by Django 5.1.7 on 2025-05-03 00:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='categorias/')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='No se permiten caracteres especiales. Solo letras, números y espacios.', regex='^[a-zA-Z0-9 ]+$')])),
                ('apellidos', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='No se permiten caracteres especiales. Solo letras, números y espacios.', regex='^[a-zA-Z0-9 ]+$')])),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='No se permiten caracteres especiales. Solo letras, números y espacios.', regex='^[a-zA-Z0-9 ]+$')])),
                ('deben', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('abonos', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('restante', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='No se permiten caracteres especiales. Solo letras, números y espacios.', regex='^[a-zA-Z0-9 ]+$')])),
                ('precio', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('categoria', models.CharField(choices=[('1', 'Cervezas'), ('2', 'Aguardiente'), ('3', 'Gaseosas'), ('4', 'Alta'), ('5', 'Ron'), ('6', 'Otros')], default='1', max_length=1)),
                ('foto', models.ImageField(upload_to='productos/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios.', regex='^[a-zA-Z ]+$')])),
                ('apellidos', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios.', regex='^[a-zA-Z ]+$')])),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe ser válido.', regex='^\\+?\\d{10,15}$')])),
                ('correo', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Correo electrónico inválido.')])),
                ('clave', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='La clave solo puede contener letras, números y caracteres especiales.', regex='^[a-zA-Z0-9@#$%^&+=]*$')])),
                ('documento', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El documento debe ser un número válido.', regex='^\\d{5,20}$')])),
                ('rol', models.IntegerField(choices=[(1, 'EMPLEADOS'), (2, 'ADMINISTRADOR')], default=1)),
                ('salario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Pagado')], default=1)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_cliente_carrito', to='Bar.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abonos', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('restante', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_cliente_deuda', to='Bar.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('mesa', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('carrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Bar.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Bar.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk3_producto_categoria', to='Bar.categoria')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk2_producto_categoria', to='Bar.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_inicio', models.TimeField()),
                ('horas_fin', models.TimeField()),
                ('fecha', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bar.usuario')),
            ],
        ),
    ]
