# Generated by Django 4.2.9 on 2025-05-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bar', '0002_alter_carrito_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
