# Generated by Django 4.2 on 2025-05-06 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bar', '0003_alter_producto_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductoCategoria',
        ),
    ]
