# Generated by Django 4.2 on 2025-05-06 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bar', '0004_delete_productocategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='Bar.categoria'),
        ),
    ]
