# Generated by Django 4.2 on 2025-05-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bar', '0005_producto_estado_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1),
        ),
    ]
