# Generated by Django 4.2 on 2025-05-06 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bar', '0007_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Bar.usuario'),
        ),
    ]
