# Generated by Django 4.2 on 2025-05-09 03:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bar', '0009_usuario_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$PZBPvqAPw36j1AhlNT5VYO$mbakAiOiXo5GTraPDgLQR8w4G97/oENt1rl6NxK0tgY=', max_length=128, validators=[django.core.validators.RegexValidator(message='La clave solo puede contener letras, números y caracteres especiales.', regex='^[a-zA-Z0-9@#$%^&+=]*$')]),
        ),
    ]
