# Generated by Django 4.2 on 2025-05-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bar', '0010_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$Xu9nc7Plw68F1Nm827YHEf$//3knCHwQw1Bh+w5nSB+zKhdF28TYg53WYl6sS79wkw=', max_length=128),
        ),
    ]
