# Generated by Django 4.2 on 2025-05-09 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bar', '0011_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$sptL8CkS6v2lq12JEWIUVt$0fx1hH6uijFPgm3IwjwLn96hBCc0fLO3dCH4JzoBSRM=', max_length=128, validators=[django.core.validators.RegexValidator(message='La clave solo puede contener letras, números y caracteres especiales.', regex='^[a-zA-Z0-9@#$%^&+=]*$')]),
        ),
    ]
